added code for medium complexity problem2- Number pattern
deepakghadge19/SDET-Project pull request #10
Opened 2023-03-21 15:19 UTC by deepakghadge19

added code for medium complexity problem2

2023-03-22 06:38 UTC, amitsahu8 requested changes

2023-03-22 06:38 UTC, amitsahu8 commented on src/mediumComplexityProblem2/NumberPattern.java
> +        p1.pattern();
pass the argument and check for the correct output

2023-03-24 10:49 UTC, rohitlamsonge66 approved these changes

2023-03-24 11:22 UTC, vrushalee123 approved these changes

2023-03-28 13:37 UTC, amitsahu8 approved these changes

2023-03-28 13:37 UTC, merged