Added code for class and constructors
deepakghadge19/SDET-Project pull request #8
Opened 2023-03-17 07:21 UTC by deepakghadge19

Added code for classes and constructors

2023-03-17 12:05 UTC, vrushalee123 requested changes

2023-03-17 12:05 UTC, vrushalee123 commented on src/class_Constructor_AccessModifiers_17March2023/CuboidConstructorDemo.java
> +	int width;
declare variables as private

2023-03-17 12:05 UTC, vrushalee123 commented on src/class_Constructor_AccessModifiers_17March2023/CuboidConstructorDemo.java
> +	CuboidConstructorDemo(int width, int height, int depth) {
Make constructor public

2023-03-17 12:05 UTC, vrushalee123 commented on src/class_Constructor_AccessModifiers_17March2023/StudentClassDemo.java
> +	String name;
Make variable always as private.

2023-03-17 14:21 UTC, deepakghadge19 commented on src/class_Constructor_AccessModifiers_17March2023/CuboidConstructorDemo.java
> +	int width;
Done! Declared variable as private

2023-03-17 14:21 UTC, deepakghadge19 commented on src/class_Constructor_AccessModifiers_17March2023/CuboidConstructorDemo.java
> +	CuboidConstructorDemo(int width, int height, int depth) {
Done

2023-03-22 06:32 UTC, amitsahu8 approved these changes

2023-03-27 11:48 UTC, merged